sudo: required
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
      env: PYCOV="--cov=plumbum"
    - python: 3.3
    - python: 3.4
    - python: 3.5
      env: PYCOV="--cov=plumbum"
    - python: nightly
    - python: pypy
    - language: generic
      os: osx
    - language: generic
      os: osx
      env: PY3=3

install: .ci/travis.sh
script: cd tests && python$PY3 -m pytest $PYCOV
after_success:
    - if [[ $PYCOV ]]; then
          coveralls;
      fi

notifications:
    email:
        on_success: change
        on_failure: change
