sudo: required
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: nightly
    - python: pypy
    - language: generic
      os: osx
      env: PYTHON_VERSION=2
    - language: generic
      os: osx
      env: PYTHON_VERSION=3

install: .ci/travis.sh
script: nosetests -vv -d

notifications:
    email:
        on_success: change
        on_failure: change
